<Project>
    <ItemGroup>
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0"/>
        <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0"/>
        <PackageVersion Include="Nerdbank.GitVersioning" Version="3.9.50"/>
        <PackageVersion Include="Scriban.Signed" Version="7.2.5"/>
        <PackageVersion Include="Spectre.Console" Version="0.50.0"/>
        <PackageVersion Include="TUnit" Version="0.6.123"/>
    </ItemGroup>
</Project>
